== Groovy

This example shows how to use Groovy with extra dependencies in Camel JBang.

The route uses `JsonSlurper` and `JsonOutput` from the `groovy-json` module
to parse a JSON string, enrich it, and log the result.

The extra dependency `org.apache.groovy:groovy-json` is declared in
`application.properties` using the `camel.jbang.dependencies` property.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run Camel JBang with `camel` as shown below.

=== How to run

You can run this example using:

[source,sh]
----
$ camel run *
----

The extra Groovy dependency is configured in `application.properties`:

[source,properties]
----
camel.jbang.dependencies=org.apache.groovy:groovy-json:4.0.27
----

You can also declare dependencies as a modeline comment at the top of the YAML route file:

[source,yaml]
----
#//DEPS org.apache.groovy:groovy-json:4.0.27
----

Or pass the dependency on the command line:

[source,sh]
----
$ camel run groovy.camel.yaml --dep=org.apache.groovy:groovy-json:4.0.27
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
